/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as OauthGoogleCalendarReturnRouteImport } from './routes/oauth/google-calendar/return'
import { Route as OauthGoogleDriveReturnRouteImport } from './routes/oauth/google-drive/return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleCalendarReturnRoute =
  OauthGoogleCalendarReturnRouteImport.update({
    id: '/oauth/google-calendar/return',
    path: '/oauth/google-calendar/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const OauthGoogleDriveReturnRoute = OauthGoogleDriveReturnRouteImport.update({
  id: '/oauth/google-drive/return',
  path: '/oauth/google-drive/return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/patterns': typeof PatternsRoute
  '/api/chat': typeof ApiChatRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/patterns': typeof PatternsRoute
  '/api/chat': typeof ApiChatRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/patterns': typeof PatternsRoute
  '/api/chat': typeof ApiChatRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/patterns'
    | '/api/chat'
    | '/oauth/google-calendar/return'
    | '/oauth/google-drive/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/patterns'
    | '/api/chat'
    | '/oauth/google-calendar/return'
    | '/oauth/google-drive/return'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/patterns'
    | '/api/chat'
    | '/oauth/google-calendar/return'
    | '/oauth/google-drive/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  PatternsRoute: typeof PatternsRoute
  ApiChatRoute: typeof ApiChatRoute
  OauthGoogleCalendarReturnRoute: typeof OauthGoogleCalendarReturnRoute
  OauthGoogleDriveReturnRoute: typeof OauthGoogleDriveReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google-calendar/return': {
      id: '/oauth/google-calendar/return'
      path: '/oauth/google-calendar/return'
      fullPath: '/oauth/google-calendar/return'
      preLoaderRoute: typeof OauthGoogleCalendarReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google-drive/return': {
      id: '/oauth/google-drive/return'
      path: '/oauth/google-drive/return'
      fullPath: '/oauth/google-drive/return'
      preLoaderRoute: typeof OauthGoogleDriveReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  PatternsRoute: PatternsRoute,
  ApiChatRoute: ApiChatRoute,
  OauthGoogleCalendarReturnRoute: OauthGoogleCalendarReturnRoute,
  OauthGoogleDriveReturnRoute: OauthGoogleDriveReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
